spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_firebaseserver?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8083  
reaktor:
  publicKeyFile: C:\claves\public_key.pem
  privateKeyFile: C:\claves\private_key.pem
  googleCredentialsFile: C:\claves\firebaseGoogleCredentials.json
  urlCors: http://localhost:5173, http://localhost:5174, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173, http://localhost:8084